### ISSUE TITLE
Can't make non-nullable interface field without resolver in strict mode

### ISSUE THREAD

**Issue by nimobeeren** [graphql-nexus/nexus#804] opened 2021-01-27 19:57 UTC
I'm running into a type error when defining a `nonNull` field on an `interfaceType`:

```ts
Vehicle: interfaceType({
  name: "Vehicle",
  resolveType: () => "Car" as const,
  definition(t) {
    t.nonNull.string("brand"); // ts(2554): Expected 2 arguments, but got 1.
  },
}),
```

Adding an empty object as second argument to `string` gives a different error: `Property 'resolve' is missing in type '{}'`.

If this were not an `interfaceType` but instead an `objectType`, then the error would be expected, since the non-nullable field must be resolved on the object. However, since it is an interface, it is up to the implementing object to provide a `resolve` function.

This is only happening in TypeScript strict mode. More specifically, setting `"strictNullChecks": false` in `tsconfig.json` makes the error go away.

Here is a [working CodeSandbox](https://codesandbox.io/s/pedantic-fermi-qxdmg?file=/index.ts).

**Comment by Sytten** [comment] 2021-02-09 21:17
Yeah I got the same error @jasonkuhrt

**Comment by jasonkuhrt** [comment] 2021-02-09 21:19
@Sytten I believe this is a duplicate of https://github.com/graphql-nexus/nexus/issues/800

**Comment by Sytten** [comment] 2021-02-09 22:17
Agreed closing as duplicate

**Closed by Sytten** 2021-02-09 22:17 UTC
Labels: note/duplicate, scope/types, type/bug
