### ISSUE TITLE
Generate schema artifacts inside node_modules/nexus by default

### ISSUE THREAD

**Issue by liadmat** [graphql-nexus/nexus#885] opened 2021-04-10 15:09 UTC
Loving Nexus so far, but one thing that bothers me is that in order to generate types it needs to "pollute" the codebase with the generated artifacts, as opposed to a more self-contained approach.

Personally, I really like how Prisma does it, where artifacts are generated inside of node_modules (node_modules/.prisma/client). 

How do you feel about making this the default behavior, or through a config in `makeSchema`?

**Comment by jasonkuhrt** [comment] 2021-04-12 03:16
Yep, duplicate of https://github.com/graphql-nexus/nexus/issues/657

**Closed by jasonkuhrt** 2021-04-12 03:16 UTC
